id: A2059B4BA
title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
  Light'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:48:37.569252
  last_modified_at: 2022-03-01 01:48:37.569263
